import pandas as pd

df = pd.read_csv('empleos_tecnoempleo.csv')

print('='*100)
print('DATASET ENRIQUECIDO - empleos_tecnoempleo.csv')
print('='*100)
print()
print('📊 INFORMACIÓN GENERAL:')
print(f'  Total de registros: {len(df)}')
print(f'  Total de columnas: {len(df.columns)}')
print()
print('📌 COLUMNAS DISPONIBLES:')
for i, col in enumerate(df.columns, 1):
    print(f'  {i}. {col}')
print()
print('📈 ESTADÍSTICAS DEL DATASET:')
print(f'  - Categorías: {df["Categoría"].nunique()} ({" / ".join(df["Categoría"].unique())})')
print(f'  - Empresas únicas: {df["Empresa"].nunique()}')
print(f'  - Localidades únicas: {df["Localidad"].nunique()}')
print()
print('📍 TOP LOCALIDADES:')
for loc, count in df['Localidad'].value_counts().head(8).items():
    print(f'  • {loc}: {count} empleos')
print()
print('💼 EXPERIENCIA DETECTADA:')
exp_counts = df['Experiencia'].value_counts()
for exp, count in exp_counts.items():
    print(f'  • {exp}: {count} empleos')
print()
print('💰 SALARIOS ENCONTRADOS (muestra):')
print(df['Salario'].value_counts().head(5))
print()
print('='*100)
print('MUESTRA DETALLADA (primeros 5 empleos):')
print('='*100)
for idx, row in df.head(5).iterrows():
    print()
    print(f"Nº {row['Nº']} - {row['Categoría']}")
    print(f"  Título: {row['Título']}")
    print(f"  Empresa: {row['Empresa']}")
    print(f"  Localidad: {row['Localidad']}")
    print(f"  Stack: {row['Stack Tecnológico']}")
    print(f"  Salario: {row['Salario']}")
    print(f"  Experiencia: {row['Experiencia']}")
    print(f"  Contrato: {row['Tipo Contrato']}")
    print()
